### ISSUE TITLE
There is a shorthand for foreach

### ISSUE THREAD

**Issue by magyarg** [kadli01/splendexexpenses#11]
https://github.com/kadli01/splendexexpenses/blob/502cce0f0fc8c863ceae0f468080073b820c0ec0/account.php#L23

You can use an alternative format of foreach in the view/template files:

`<?php foreach($items as $item): ?>`
   `<h1><?php $item['index'];  ?></h1>`
`<?php endforeach; ?>`

This way you don't have to break and replace all the HTML tags as string

**Comment by kadli01** [comment]
fixed
