### ISSUE TITLE
Configuration file changes

### ISSUE THREAD

**Issue by magyarg** [kadli01/splendexexpenses#13]
https://github.com/kadli01/splendexexpenses/blob/0fa50b860e5552cfdcb4cd7191ce14f942aecf66/resources/functions/config.php#L7

I saw You were trying to modify the configuration Scheme by creating a class for it. This wasn't the goal actually. You can create a new array to define the credentials and convert it into an array of objects so it can be used the following format: `$config–>host`.

**Comment by kokxter33** [comment]
Fixed
