### ISSUE TITLE
Headers Already Sent Error

### ISSUE THREAD

**Issue by andretimar** [kadli01/splendexexpenses#16]
After doing a clean install, a PHP warning appeared above the login form:

> Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /Users/seal/Sites/splendexexpenses/resources/include/head.php:1) in /Users/seal/Sites/splendexexpenses/index.php on line 2
 
This is caused by declaring the **session_start();** in the second line of index.php instead of the first. Also, make sure there is no tab/whitespace before this in the file.

**Comment by kokxter33** [comment]
Fixed
