### ISSUE TITLE
Account - Expenses - Incorrect date value

### ISSUE THREAD

**Issue by andretimar** [kadli01/splendexexpenses#24]
At every expense you have to display the date the user sets when creating the expense (using that datepicker) not the created_at value of the expense entry.

![screen shot 2017-11-27 at 9 58 20](https://user-images.githubusercontent.com/10631054/33258365-9a992874-d359-11e7-9d60-1016dd1ab3c2.png)

**Comment by kokxter33** [comment]
Fixed
