### ISSUE TITLE
Expenses - Create New - White screen error

### ISSUE THREAD

**Issue by andretimar** [kadli01/splendexexpenses#25]
I tried to add this for the name of the expense:

> Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Aenean lacinia bibendum nulla sed consectetur. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras justo odio, dapibus ac facilisis in, egestas eget quam.

And when I clicked Save the browser redirected me to an empty white page, I believe the database can't hold this text for the title. Add validation everywhere!

**Comment by kokxter33** [comment]
Fixed
