### ISSUE TITLE
Global - URL Protections

### ISSUE THREAD

**Issue by andretimar** [kadli01/splendexexpenses#28]
I'm able to change the accounts tab from:

`/show.php?accountId=243`

to 

`/show.php?accountId=9999999`

and it displays non existent, blank accounts but if I change it to a real account I can potentially gain access to accounts I shouldn't.

Make sure this is blocked by changing the URL and I can only access accounts from the homepage list of accounts.

**Comment by kokxter33** [comment]
Fixed
