### ISSUE TITLE
Insert a guard to check the PDO object

### ISSUE THREAD

**Issue by magyarg** [kadli01/splendexexpenses#3]
https://github.com/kadli01/splendexexpenses/blob/502cce0f0fc8c863ceae0f468080073b820c0ec0/resources/functions/connection.php#L4

When the PDO object fails during the connection it will return false or null. Check somehow and throw a new Exception:
http://php.net/manual/en/language.exceptions.php

`throw new Exception('error message')`

**Comment by kokxter33** [comment]
Fixed
