### ISSUE TITLE
Remove bindings before PDO executes

### ISSUE THREAD

**Issue by magyarg** [kadli01/splendexexpenses#6]
Consider removeing the bindParam methods before the PDO executes, You can wrap these into the execute proc. like this: 

`$sql  = 'SELECT 1 FROM user WHERE email_address = ? AND password = ?';
$stmt = $conn->prepare($sql);
$stmt->execute([$email, $password]);
$userCount = $stmt->fetchColumn();`

**Comment by kokxter33** [comment]
Fixed
