### ISSUE TITLE
Guard the return value

### ISSUE THREAD

**Issue by magyarg** [kadli01/splendexexpenses#8]
https://github.com/kadli01/splendexexpenses/blob/502cce0f0fc8c863ceae0f468080073b820c0ec0/resources/functions/login.php#L24

There can be some case when the return value will be null or simply an empty array. When this happens the $variable[0] will provide an undefined index error so we should place a guard before it.

**Comment by kokxter33** [comment]
Something like this?

if(isset($userId[0])){
    $_SESSION['user_id'] = $userId[0];
}

**Comment by magyarg** [comment]
Yes, You can add an empty check to the condition to be more specific saying: "Okay, if the $userId array is empty we should skip the body" ->

`if(!empty($userId) && isset($userId[0])){
$_SESSION['user_id'] = $userId[0];
}`

But as I said your solution is totally fine!
